In [55]:
import pandas as pd

df = pd.read_excel("C:/Users/user/Desktop/평창군데이터/평창군데이터_전처리/평창군평균소득.xlsx")
df

            행정구역 법정동명  총인구수  총가구수  가구당인구수   평균소득금액
0    강원도 평창군 평창읍   상리  8166  3646    2.24  2073.71
1    강원도 평창군 평창읍   중리  8166  3646    2.24  2414.35
2    강원도 평창군 평창읍   하리  8166  3646    2.24  2240.77
3    강원도 평창군 평창읍  천변리  8166  3646    2.24  1925.24
4    강원도 평창군 평창읍  종부리  8166  3646    2.24  2150.30
..           ...  ...   ...   ...     ...      ...
84  강원도 평창군 대관령면  병내리  5553  2891    1.92  2059.12
85  강원도 평창군 대관령면  차항리  5553  2891    1.92  2640.13
86  강원도 평창군 대관령면  횡계리  5553  2891    1.92  2633.72
87  강원도 평창군 대관령면  수하리  5553  2891    1.92  2373.60
88  강원도 평창군 대관령면  용산리  5553  2891    1.92  2881.01

[89 rows x 6 columns]

In [56]:
df['행정구역'] = df['행정구역'] + ' ' + df['법정동명']
df

                행정구역 법정동명  총인구수  총가구수  가구당인구수   평균소득금액
0     강원도 평창군 평창읍 상리   상리  8166  3646    2.24  2073.71
1     강원도 평창군 평창읍 중리   중리  8166  3646    2.24  2414.35
2     강원도 평창군 평창읍 하리   하리  8166  3646    2.24  2240.77
3    강원도 평창군 평창읍 천변리  천변리  8166  3646    2.24  1925.24
4    강원도 평창군 평창읍 종부리  종부리  8166  3646    2.24  2150.30
..               ...  ...   ...   ...     ...      ...
84  강원도 평창군 대관령면 병내리  병내리  5553  2891    1.92  2059.12
85  강원도 평창군 대관령면 차항리  차항리  5553  2891    1.92  2640.13
86  강원도 평창군 대관령면 횡계리  횡계리  5553  2891    1.92  2633.72
87  강원도 평창군 대관령면 수하리  수하리  5553  2891    1.92  2373.60
88  강원도 평창군 대관령면 용산리  용산리  5553  2891    1.92  2881.01

[89 rows x 6 columns]

In [7]:
df['행정구역']

0       강원도 평창군 평창읍 상리
1       강원도 평창군 평창읍 중리
2       강원도 평창군 평창읍 하리
3      강원도 평창군 평창읍 천변리
4      강원도 평창군 평창읍 종부리
            ...
84    강원도 평창군 대관령면 병내리
85    강원도 평창군 대관령면 차항리
86    강원도 평창군 대관령면 횡계리
87    강원도 평창군 대관령면 수하리
88    강원도 평창군 대관령면 용산리
Name: 행정구역, Length: 89, dtype: object

In [57]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

# 위도, 경도 반환하는 함수
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

In [58]:
latitude = []
longitude =[]

for i in df['행정구역']:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

In [10]:
df['경도'] = latitude
df['위도'] = longitude
df

                행정구역 법정동명  총인구수  총가구수  가구당인구수   평균소득금액         경도          위도
0     강원도 평창군 평창읍 상리   상리  8166  3646    2.24  2073.71  37.360325  128.417884
1     강원도 평창군 평창읍 중리   중리  8166  3646    2.24  2414.35  37.373680  128.404613
2     강원도 평창군 평창읍 하리   하리  8166  3646    2.24  2240.77  37.368963  128.384770
3    강원도 평창군 평창읍 천변리  천변리  8166  3646    2.24  1925.24  37.365953  128.397801
4    강원도 평창군 평창읍 종부리  종부리  8166  3646    2.24  2150.30  37.350441  128.398442
..               ...  ...   ...   ...     ...      ...        ...         ...
84  강원도 평창군 대관령면 병내리  병내리  5553  2891    1.92  2059.12  37.735915  128.624357
85  강원도 평창군 대관령면 차항리  차항리  5553  2891    1.92  2640.13  37.709009  128.680734
86  강원도 평창군 대관령면 횡계리  횡계리  5553  2891    1.92  2633.72  37.703837  128.711488
87  강원도 평창군 대관령면 수하리  수하리  5553  2891    1.92  2373.60  37.629003  128.705002
88  강원도 평창군 대관령면 용산리  용산리  5553  2891    1.92  2881.01  37.645005  128.665467

[89 rows x 8 columns]

In [12]:
df.to_csv('평창군평균소득(전처리).csv',encoding='euc-kr')

### 남북 나뉜 데이터 이용

In [89]:
df = pd.read_excel("C:/Users/user/Desktop/평창군데이터/평창군데이터_전처리/평창군평균소득(전처리2).xlsx")
df

                행정구역 남북구분    평균소득금액         경도          위도  총가구수  총인구수
0   강원도 평창군 대관령면 병내리   북부  2,059.12  37.735915  128.624357  2891  5553
1   강원도 평창군 대관령면 수하리   남부   2,373.6  37.629003  128.705002  2891  5553
2   강원도 평창군 대관령면 용산리   남부  2,881.01  37.645005  128.665467  2891  5553
3   강원도 평창군 대관령면 유천리   남부   2,133.1  37.665740  128.628490  2891  5553
4   강원도 평창군 대관령면 차항리   북부  2,640.13  37.709009  128.680734  2891  5553
..               ...  ...       ...        ...         ...   ...   ...
84   강원도 평창군 평창읍 천변리   남부  1,925.24  37.365953  128.397801  3646  8166
85    강원도 평창군 평창읍 하리   남부  2,240.77  37.368963  128.384770  3646  8166
86   강원도 평창군 평창읍 하일리   남부  2,183.27  37.392559  128.339411  3646  8166
87   강원도 평창군 평창읍 향동리   남부  1,980.86  37.378761  128.361378  3646  8166
88   강원도 평창군 평창읍 후평리   남부  2,110.87  37.384211  128.390215  3646  8166

[89 rows x 7 columns]

In [90]:
#한글 깨짐 방지 코드
from matplotlib import rc, style, font_manager
font_name = font_manager.FontProperties(fname="C:/windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
style.use('ggplot')

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [91]:
df = df.astype({'행정구역':'str'})

In [95]:
df['리'] = df['행정구역'].str.split(' ').str[3]

In [106]:
n = df[df['남북구분'] == '북부'].iloc[:,6]
s = df[df['남북구분'] == '남부'].iloc[:,6]

0     5553
4     5553
5     5553
23    5421
24    5421
25    5421
26    5421
28    5421
29    5421
30    5421
31    5421
32    2890
33    2890
34    2890
35    2890
40    8302
42    8302
43    8302
48    8302
53    8302
54    8302
Name: 총인구수, dtype: int64

In [70]:
df['평균소득금액'] = df['평균소득금액'].apply(lambda x: x.replace(',',''))

In [71]:
df = df.astype({'평균소득금액':'float'})

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역    89 non-null     object
 1   남북구분    89 non-null     object
 2   평균소득금액  89 non-null     float64
 3   경도      89 non-null     float64
 4   위도      89 non-null     float64
 5   총가구수    89 non-null     int64
 6   총인구수    89 non-null     int64
dtypes: float64(3), int64(2), object(2)
memory usage: 5.0+ KB

In [73]:
df['남북구분'].value_counts()

남부    68
북부    21
Name: 남북구분, dtype: int64

In [34]:
df.groupby('남북구분').mean()

           평균소득금액         경도          위도         총가구수         총인구수
남북구분
남부    2036.544265  37.441514  128.451972  2897.205882  6360.588235
북부    2283.559524  37.657602  128.475722  2702.238095  5780.904762

In [47]:
south = df[df['남북구분'] =='남부'].reset_index(drop=True)
south_d = south['평균소득금액']

north = df[df['남북구분'] =='북부'].reset_index(drop=True)
north_d = north['평균소득금액']

### 정규성 검정

In [62]:
import scipy.stats as stats

stats.shapiro(df['평균소득금액'])

ShapiroResult(statistic=0.9577198624610901, pvalue=0.005510285962373018)

#### 정규성 가정 위배

### 등분산 검정

In [63]:
from scipy.stats import levene

levene(south_d, north_d)

LeveneResult(statistic=5.06189964198239, pvalue=0.02698056646308864)

#### 등분산 가정 위배

In [67]:
from scipy.stats import mannwhitneyu

def mann_whitney_u_test(data1, data2):
    stat, p = mannwhitneyu(data1, data2)
    alpha = 0.05
    
    print('statistic:',stat)
    print('p-value:',p)
    print('-'*50)
    
    if p > alpha:
        print("fail to reject H0")
    else:
        print("reject H0")

mann_whitney_u_test(south_d,north_d)

statistic: 406.0
p-value: 0.0014825815280291442
--------------------------------------------------
reject H0

In [54]:
from scipy import stats

t_statistic, p_value  = stats.ttest_ind(south_d, north_d)

print('statistic:',t_statistic)
print('p_value:',p_value)
print('-'*50)
if p_value > 0.05:
    print("남부와 북부의 평균소득에는 차이가 없다")
else:
    print("남부와 북부의 평균소득에는 차이가 있다.")

statistic: -3.716950641849507
p_value: 0.0003560046173682467
--------------------------------------------------
남부와 북부의 평균소득에는 차이가 있다.